export const DEVELOPER_LOADING = "DEVELOPER_LOADING";
export const GET_DEVELOPERS = "GET_DEVELOPERS";
export const GET_DEVELOPER = "GET_DEVELOPER";
export const CREATE_DEVELOPER = "CREATE_DEVELOPER";
export const EDIT_DEVELOPER = "EDIT_DEVELOPER";
export const BLACKLIST_DEVELOPER = "BLACKLIST_DEVELOPER";
export const ARCHIVE_DEVELOPER = "ARCHIVE_DEVELOPER";
export const DEVELOPER_FAILED = "DEVELOPER_FAILED";
export const SEARCH_DEVELOPER = "SEARCH_DEVELOPER";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_RESUME = "UPLOAD_RESUME";
